### ISSUE TITLE
Problem starting Container

### ISSUE THREAD

**Issue by svalcken** [cloudycube/docker-strongswan#3] opened 2018-11-30 00:08 UTC
Hello,

following 2 problems, i have:
the first, often and 9/10 trys on commands like list/add user:
/docker-startup/run-startup.sh: /docker-startup/10-initial.startup/startup: /usr/bin/python3: bad interpreter: Text file busy

the second on try to run the container:
[note] External CA certificate was not found. Using the internal PKI for client authentication.
[info] Loading kernel module 'af_key' not necessary, it is already loaded.
[info] Configuring networking...
[info] => Configuring firewall
[info] => Enabling masquerading for IPv4
[info] => Enabling masquerading for IPv6
[info] --------------------------------------------------------------------------------
**[info] --- Griffin+ Container Startup System exited with code (0)**
Unlinking stale socket /var/run/supervisor.sock

The container are shutdown without any error. Certificates are all made and show on startup.

**Comment by ravenpride** [comment] 2018-12-25 20:54
Hello Svalcken,

I've tried to reproduce the issue, but I couldn't. Everything works as expected on my host. Do you have the chance to have it run on another docker host?

Btw: I've updated the image to use Ubuntu 18.04 LTS and StrongSwan 4.7.1. Could you just give it another try, please?

**Comment by ravenpride** [comment] 2018-12-26 09:41
I've done some googling for the problem you encountered. It seems that the Python script is already opened with write access by some other process. Do you add multiple users concurrently, so the script is called multiple times as well?

**Comment by ravenpride** [comment] 2019-08-18 19:18
As I cannot reproduce the issue and no further information is coming, I'll close the issue.
Feel free to re-open it, if necessary.

**Comment by Perchework** [comment] 2019-08-28 06:41
Hi,

I've got this error too on an old server:  
`/docker-startup/run-startup.sh: /docker-startup/10-initial.startup/startup: /usr/bin/python3: bad interpreter: Text file busy`

This problem is here when the docker's storage driver is `aufs`.
I switch to overlay2 and the problem is gone :)

**Comment by ravenpride** [comment] 2019-08-28 15:26
Thank you for the hint!

I haven't seen this error for a long time - mabe due to many people switching over from *aufs* to *overlay* or *overlay2*. By the way, *aufs* has terrible performance. You should prefer *overlay* - or even better *overlay2* - whenever you can.

**Closed as completed by ravenpride** 2019-08-28 15:26 UTC
